### PR TITLE
Adding support for fc26

### PR DESCRIPTION
**Pull request by gbenhaim**
Verified locally.

https://github.com/lago-project/lago-demo/issues/39 should be added too.

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by eedri** [comment]
We need new lago-ost-plugin pkg for fc26 before we can test it.

**Comment by gbenhaim** [comment]
Added fc26 job today, we can take lago-ost-plugin from unstable http://resources.ovirt.org/repos/lago/unstable/0.0/latest/rpm/fc26/noarch/

**Comment by ifireball** [comment]
probably need to ensure repoman has stable and ongoing FC26 support before doing that

**Comment by gbenhaim** [comment]
ci test please

**Pull request merged**
