### PR TITLE
Install missing deps for ost

### PR DESCRIPTION
**Pull request by rgolangh**

### CODE REVIEW

**Comment by gbenhaim** [comment]
Thanks for the PR. 
I think that this one should be part of OST, otherwise it will make Lago's install script
OST specific (it already installs oVirt SDK, and I don't really like it).

**Comment by rgolangh** [comment]
I would prefer to containerize the bastion host which spins run_suite in OST, and that will keep lago deps to its bare minimum and OST deps unified and stable.
Namely - let create an OST runner container. If you got a issue for that I'll link it here, if not I'll create it

**Comment by rgolangh** [comment]
With regard to what you said about this belonging to ost - currently I don't think there is a setup stage for ost - you just clone the sources and run your suite. Even this install script is just running run_suite in the end after pulling the sources https://github.com/lago-project/lago-demo/blob/9a160e6be3ad62b75fc1b183ea283ee5c7ddc69d/install_scripts/install_lago.sh#L240

**Comment by gbenhaim** [comment]
ci test please

**Pull request closed without merging**
