### PR TITLE
Provide a minimal example

### PR DESCRIPTION
**Pull request by karmab**
Provide a minimal example with only 2 vms and no metadata, and move the jenkins example to a dedicated LagoinitFile.jenkins

### CODE REVIEW

**Comment by ovirt-infra** [comment]
The commiter is not a member of organization nor whitelist. Please contact maintainer for patch verification.

**Comment by ovirt-infra** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Sorry for the late response, this was somehow missed from the alerts until now, is it still relevant?

**Comment by nvgoldin** [comment]
Closing for now, feel free to reopen.

**Pull request closed without merging**
