### PR TITLE
install also virt-viewer

### PR DESCRIPTION
**Pull request by eedri**
Signed-off-by: Eyal Edri <eedri@redhat.com>

### CODE REVIEW

**Comment by mykaul** [comment]
Why do we need it? Doesn't require X and stuff?

**Comment by eedri** [comment]
Its part of the requirements for Lago demo, if we don't need it then lets remove it from the guide.

**Comment by mykaul** [comment]
I work without it upstream, not sure it's needed downstream.

**Comment by eedri** [comment]
The demo tool is only for d/s, and this install script is mostly for it, so the question is if its really needed.
@gbenhaim @nvgoldin ?

**Comment by nvgoldin** [comment]
@eedri - per Lago/OST - its not needed(downstream nor upstream). 
So I think it can be safely removed, unless there was a different reason for including it there.

**Pull request closed without merging**
