### PR TITLE
[do not merge] automation: add centos7.2 to tested platforms

### PR DESCRIPTION
**Pull request by nvgoldin**
Signed-off-by: Nadav Goldin <ngoldin@redhat.com>

### CODE REVIEW

**Comment by mykaul** [comment]
With EL7.3 released so long ago, not sure I see the point.

**Comment by eedri** [comment]
Yea, seems like qmeu-kvm already requires 7.3 rpms, so not sure we can support 7.2

**Comment by eedri** [comment]
Let's remove the 7.2 support in the demo tool doc

**Comment by nvgoldin** [comment]
Sure then, closing.

BTW - the CI is failing, there is some bug with the exit code.

**Comment by nvgoldin** [comment]
reopening to test the CI bug - sorry for the noise.

**Pull request closed without merging**
